package app.cardium.tcgdex.sdk.embedded

import kotlinx.serialization.Serializable

/**
 * Metadata for embedded catalog generation.
 * Used for cache versioning based on generation timestamp.
 *
 * Generated by GenerateEmbeddedCatalog.kt and stored as catalog-metadata.json
 * in each language directory (e.g., tcgdex/en/catalog-metadata.json).
 *
 * The generatedAt timestamp is used as the cache version for SetSheet card caches,
 * ensuring automatic cache invalidation when the catalog is regenerated.
 */
@Serializable
data class CatalogMetadata(
    /**
     * Metadata format version (currently 1)
     */
    val version: Int = 1,
    /**
     * Unix timestamp in milliseconds when the catalog was generated
     * Used as cache version: "tcgdex_set_cards_{generatedAt}_{lang}_{setId}"
     */
    val generatedAt: Long,
    /**
     * Language code for this catalog (e.g., "en", "fr", "ja")
     */
    val language: String,
)
