package app.cardium.tcgdex.sdk.embedded

object EmbeddedCatalogData {
  private val artistFiles: List<String> = listOf(
    """
global/artists/Hideki_Ishikawa.json
""",
    """
global/artists/Yuu_Nishida.json
""",
    """
global/artists/kawayoo.json
""",
    """
global/artists/Souichirou_Gunjima.json
""",
    """
global/artists/toriyufu.json
""",
    """
global/artists/akagi.json
""",
    """
global/artists/nagimiso.json
""",
    """
global/artists/Nurikabe.json
""",
    """
global/artists/PLANETA_CG_Works.json
""",
    """
global/artists/Tetsu_Kayama.json
""",
    """
global/artists/miki_kudo.json
""",
    """
global/artists/Anesaki_Dynamic.json
""",
    """
global/artists/Sumiyoshi_Kizuki.json
""",
    """
global/artists/AKIRA_EGAWA.json
""",
    """
global/artists/Satoshi_Shirai.json
""",
    """
global/artists/Kouki_Saitou.json
""",
    """
global/artists/match.json
""",
    """
global/artists/MAHOU.json
""",
    """
global/artists/Atsushi_Furusawa.json
""",
    """
global/artists/DOM.json
""",
    """
global/artists/SATOSHI_NAKAI.json
""",
    """
global/artists/Akira_Komayama.json
""",
    """
global/artists/rika.json
""",
    """
global/artists/Shin_Nagasawa.json
""",
    """
global/artists/sui.json
""",
    """
global/artists/otumami.json
""",
    """
global/artists/Kyoko_Umemoto.json
""",
    """
global/artists/Tika_Matsuno.json
""",
    """
global/artists/Apios.json
""",
    """
global/artists/Asako_Ito.json
""",
    """
global/artists/Takumi_Wada.json
""",
    """
global/artists/Kazumasa_Yasukuni.json
""",
    """
global/artists/PLANETA_Tsuji.json
""",
    """
global/artists/matazo.json
""",
    """
global/artists/tetsuya_koizumi.json
""",
    """
global/artists/Midori_Harada.json
""",
    """
global/artists/Naoyo_Kimura.json
""",
    """
global/artists/saino_misaki.json
""",
    """
global/artists/MINAMINAMI_Take.json
""",
    """
global/artists/Shinya_Komatsu.json
""",
    """
global/artists/Atsuko_Nishida.json
""",
    """
global/artists/Eri_Yamaki.json
""",
    """
global/artists/burari.json
""",
    """
global/artists/Yukihiro_Tada.json
""",
    """
global/artists/Masakazu_Fukuda.json
""",
    """
global/artists/Tomokazu_Komiya.json
""",
    """
global/artists/Masa.json
""",
    """
global/artists/OKACHEKE.json
""",
    """
global/artists/Mina_Nakai.json
""",
    """
global/artists/Hajime_Kusajima.json
""",
    """
global/artists/Nisota_Niso.json
""",
    """
global/artists/Taiga_Kayama.json
""",
    """
global/artists/Shiburingaru.json
""",
    """
global/artists/Sekio.json
""",
    """
global/artists/Mizue.json
""",
    """
global/artists/Yukiko_Baba.json
""",
    """
global/artists/Minahamu.json
""",
    """
global/artists/IKEDA_Saki.json
""",
    """
global/artists/Yuriko_Akase.json
""",
    """
global/artists/Kagemaru_Himeno.json
""",
    """
global/artists/Naoki_Saito.json
""",
    """
global/artists/sowsow.json
""",
    """
global/artists/Toyste_Beach.json
""",
    """
global/artists/HYOGONOSUKE.json
""",
    """
global/artists/Shimaris_Yukichi.json
""",
    """
global/artists/osare.json
""",
    """
global/artists/Keisin.json
""",
    """
global/artists/Sanosuke_Sakuma.json
""",
    """
global/artists/Orca.json
""",
    """
global/artists/hncl.json
""",
    """
global/artists/AYUMI_ODASHIMA.json
""",
    """
global/artists/Whisker.json
""",
    """
global/artists/PLANETA_Igarashi.json
""",
    """
global/artists/Ryota_Murayama.json
""",
    """
global/artists/kodama.json
""",
    """
global/artists/tono.json
""",
    """
global/artists/Misa_Tsutsui.json
""",
    """
global/artists/danciao.json
""",
    """
global/artists/Yumi.json
""",
    """
global/artists/Taiga_Kasai.json
""",
    """
global/artists/OKUBO.json
""",
    """
global/artists/Shigenori_Negishi.json
""",
    """
global/artists/Aya_Kusube.json
""",
    """
global/artists/Saya_Tsuruta.json
""",
    """
global/artists/Takeshi_Nakamura.json
""",
    """
global/artists/Shibuzoh.json
""",
    """
global/artists/Kazuma_Koda.json
""",
    """
global/artists/Yuka_Tanaka.json
""",
    """
global/artists/GIDORA.json
""",
    """
global/artists/Studio_Bora_Inc.json
""",
    """
global/artists/GOSSAN.json
""",
    """
global/artists/Ryuta_Fuse.json
""",
    """
global/artists/Krgc.json
""",
    """
global/artists/Shinji_Kanda.json
""",
    """
global/artists/Suwama_Chiaki.json
""",
    """
global/artists/NC_Empire.json
""",
    """
global/artists/Hasuno.json
""",
    """
global/artists/Miki_Tanaka.json
""",
    """
global/artists/Kanako_Eo.json
""",
    """
global/artists/PLANETA_Saito.json
""",
    """
global/artists/chibi.json
""",
    """
global/artists/Kariya.json
""",
    """
global/artists/Ryo_Ueda.json
""",
    """
global/artists/Hitoshi_Ariga.json
""",
    """
global/artists/Teeziro.json
""",
    """
global/artists/Kanami_Ogata.json
""",
    """
global/artists/Hiroyuki_Yamamoto.json
""",
    """
global/artists/Uta.json
""",
    """
global/artists/Amelicart.json
""",
    """
global/artists/Cona_Nitanda.json
""",
    """
global/artists/You_Iribi.json
""",
    """
global/artists/whomor_Inc.json
""",
    """
global/artists/Ayaka_Yoshida.json
""",
    """
global/artists/Jerky.json
""",
    """
global/artists/Jiro_Sasumo.json
""",
    """
global/artists/Mkayu.json
""",
    """
global/artists/Sachiko_Adachi.json
""",
    """
global/artists/kirisAki.json
""",
    """
global/artists/Ounishi.json
""",
    """
global/artists/REND.json
""",
    """
global/artists/Kuroimori.json
""",
    """
global/artists/Koji_Nakata.json
""",
    """
global/artists/Yoko_Hishida.json
""",
    """
global/artists/Saboteri.json
""",
    """
global/artists/5ban_Graphics.json
""",
    """
global/artists/Rianti_Hidayat.json
""",
    """
global/artists/Narumi_Sato.json
""",
    """
global/artists/hatachu.json
""",
    """
global/artists/Susumu_Maeya.json
""",
    """
global/artists/Kurata_So.json
""",
    """
global/artists/KIYOTAKA_OSHIYAMA.json
""",
    """
global/artists/Raita_Kazama.json
""",
    """
global/artists/0313.json
""",
    """
global/artists/PLANETA_Mochizuki.json
""",
    """
global/artists/Ligton.json
""",
    """
global/artists/Haru_Akasaka.json
""",
    """
global/artists/KEIICHIRO_ITO.json
""",
    """
global/artists/Scav.json
""",
    """
global/artists/PLANETA_Yamashita.json
""",
    """
global/artists/Yuka_Morii.json
""",
    """
global/artists/Taira_Akitsu.json
""",
    """
global/artists/Megumi_Mizutani.json
""",
    """
global/artists/ryoma_uratsuka.json
""",
    """
global/artists/Nagomi_Nijo.json
""",
    """
global/artists/Yuya_Oka.json
""",
    """
global/artists/nisimono.json
""",
    """
global/artists/En_Morikura.json
""",
    """
global/artists/OOYAMA.json
""",
    """
global/artists/Yoriyuki_Ikegami.json
""",
    """
global/artists/Uninori.json
""",
    """
global/artists/Yoshinobu_Saito.json
""",
    """
global/artists/okayamatakatoshi.json
""",
    """
global/artists/GOTO_minori.json
""",
    """
global/artists/buchi.json
""",
    """
global/artists/Masako_Tomii.json
""",
    """
global/artists/yuu.json
""",
    """
global/artists/Noriaki_Tanimura.json
""",
    """
global/artists/Yoshimi_Miyoshi.json
""",
    """
global/artists/Hisao_Nakamura.json
""",
    """
global/artists/Ayako_Ozaki.json
""",
    """
global/artists/Toshinao_Aoki.json
""",
    """
global/artists/Terada_Tera.json
""",
    """
global/artists/SIE_NANAHARA.json
""",
    """
global/artists/Natsumi_Yoshida.json
""",
    """
global/artists/Fujimoto_Gold.json
""",
    """
global/artists/Makura_Tami.json
""",
    """
global/artists/kamonabe.json
""",
    """
global/artists/June.json
""",
    """
global/artists/Mousho.json
""",
    """
global/artists/kantaro.json
""",
    """
global/artists/aspara.json
""",
    """
global/artists/Mitsuhiro_Arita.json
""",
    """
global/artists/Yoshioka.json
""",
    """
global/artists/LINNE.json
""",
    """
global/artists/Gapao.json
""",
    """
global/artists/Oswaldo_KATO.json
""",
    """
global/artists/Tomowaka.json
""",
    """
global/artists/hechima.json
""",
    """
global/artists/USGMEN.json
""",
    """
global/artists/imoniii.json
""",
    """
global/artists/kurumitsu.json
""",
    """
global/artists/Gemi.json
""",
    """
global/artists/mele.json
""",
    """
global/artists/mashu.json
""",
    """
global/artists/Tsuyoshi_Nagano.json
""",
    """
global/artists/Tomomi_Ozaki.json
""",
    """
global/artists/takashi_shiraishi.json
""",
    """
global/artists/YASHIRO_Nanaco.json
""",
    """
global/artists/Rond.json
""",
    """
global/artists/Dsuke.json
""",
    """
global/artists/cochi8i.json
""",
    """
global/artists/Mori_Yuu.json
""",
    """
global/artists/HAGIYA_Kaoru.json
""",
    """
global/artists/Nelnal.json
""",
    """
global/artists/aoki.json
""",
    """
global/artists/Masako_Yamashita.json
""",
    """
global/artists/Ken_Sugimori.json
""",
    """
global/artists/takuyoa.json
""",
    """
global/artists/Hiroki_Asanuma.json
""",
    """
global/artists/Pani_Kobayashi.json
""",
    """
global/artists/Mugi_Hamada.json
""",
    """
global/artists/Kedamahadaitai_Yawarakai.json
""",
    """
global/artists/N-DESIGN_Inc.json
""",
    """
global/artists/Eske_Yoshinob.json
""",
    """
global/artists/inose_yukie.json
""",
    """
global/artists/Kouji_Tajima.json
""",
    """
global/artists/Shizurow.json
""",
    """
global/artists/Yusuke_Ohmura.json
""",
    """
global/artists/TOKIYA.json
""",
    """
global/artists/Kent_Kanetsuna.json
""",
    """
global/artists/Noriko_Hotta.json
""",
    """
global/artists/Daisuke_Iwamoto.json
""",
    """
global/artists/Yuri_Umemura.json
""",
    """
global/artists/Hideaki_Hakozaki.json
""",
    """
global/artists/BERUBURI.json
""",
    """
global/artists/HiRON.json
""",
    """
global/artists/Tomoaki_Imakuni.json
""",
    """
global/artists/IllusDirecThe_Pokmon_Company_Art_Team.json
""",
    """
global/artists/Tomohiro_Kitakaze.json
""",
    """
global/artists/Maiko_Fujiwara.json
""",
    """
global/artists/Reiko_Tanoue.json
""",
    """
global/artists/James_Turner.json
""",
    """
global/artists/Keiji_Kinebuchi.json
""",
    """
global/artists/Takumi_Akabane.json
""",
    """
global/artists/Shin-ichi_Yoshida.json
""",
    """
global/artists/Gakuji_Nomoto.json
""",
    """
global/artists/Christopher_Rush.json
""",
    """
global/artists/Hironobu_Yoshida.json
""",
    """
global/artists/Craig_Turvey.json
""",
    """
global/artists/Kunihiko_Yuyama.json
""",
    """
global/artists/Hideki_Kazama.json
""",
    """
global/artists/Benimaru_Itoh.json
""",
    """
global/artists/unknown.json
""",
    """
global/artists/Hiromichi_Sugiyama.json
""",
    """
global/artists/Hiroki_Fuchino.json
""",
    """
global/artists/Kazuo_Yazawa.json
""",
    """
global/artists/Kazuyuki_Kano.json
""",
    """
global/artists/Daisuke_Ito.json
""",
    """
global/artists/Ken_Ikuji.json
""",
    """
global/artists/Shin-ichi_Yoshikawa.json
""",
    """
global/artists/Nakaoka.json
""",
    """
global/artists/Hikaru_Koike.json
""",
    """
global/artists/Katsura_Tabata.json
""",
    """
global/artists/K_Hoshiba.json
""",
    """
global/artists/Wataru_Kawahara.json
""",
    """
global/artists/Takashi_Yamaguchi.json
""",
    """
global/artists/Rya_Ueda.json
""",
    """
global/artists/K_Utsunomiya.json
""",
    """
global/artists/MikiTanaka.json
""",
    """
global/artists/Tokumi_Akabane.json
""",
    """
global/artists/Jungo_Suzuki.json
""",
    """
global/artists/M_Akiyama.json
""",
    """
global/artists/Yosuke_Da_Silva.json
""",
    """
global/artists/T_Honda.json
""",
    """
global/artists/Atsuko_Ujiie.json
""",
    """
global/artists/Big_Mama.json
""",
    """
global/artists/Zu-Ka.json
""",
    """
global/artists/Mt_TBT.json
""",
    """
global/artists/Midroi_Harada.json
""",
    """
global/artists/Emi_Miwa.json
""",
    """
global/artists/Kyoko_Koizumi.json
""",
    """
global/artists/Motofumi_Fujiwara.json
""",
    """
global/artists/Kimiya_Masago.json
""",
    """
global/artists/Takao_Unno.json
""",
    """
global/artists/Satoshi_Ohta.json
""",
    """
global/artists/Kenkichi_Toyama.json
""",
    """
global/artists/Masahiko_Ishii.json
""",
    """
global/artists/Yusuke_Shimada.json
""",
    """
global/artists/Milky_Isobe.json
""",
    """
global/artists/Yasuki_Watanabe.json
""",
    """
global/artists/Kai_Ishikawa.json
""",
    """
global/artists/Takabon.json
""",
    """
global/artists/Tomoko_Wakai.json
""",
    """
global/artists/Asuka_Iwashita.json
""",
    """
global/artists/Aimi_Tomita.json
""",
    """
global/artists/Mark_Kraus.json
""",
    """
global/artists/Sylvia_Forrest.json
""",
    """
global/artists/Rowan_Laidlaw.json
""",
    """
global/artists/May_Do.json
""",
    """
global/artists/Katie_Gross.json
""",
    """
global/artists/Tomokazu.json
""",
    """
global/artists/Hideyuki_Nakajima.json
""",
    """
global/artists/Ken_Ikugi.json
""",
    """
global/artists/Kazuaki_Aihara.json
""",
    """
global/artists/Emi_Yoshida.json
""",
    """
global/artists/Lee_HyunJung.json
""",
    """
global/artists/Ryota_Saito.json
""",
    """
global/artists/Yusuke_Ishikawa.json
""",
    """
global/artists/Hiroaki_Ito.json
""",
    """
global/artists/Makoto_Imai.json
""",
    """
global/artists/Mikiko_Takeda.json
""",
    """
global/artists/SayaTsuruta.json
""",
    """
global/artists/CR_CG_gangs.json
""",
    """
global/artists/Imakuni.json
""",
    """
global/artists/Etsuya_Hattori.json
""",
    """
global/artists/Keiko_Fukuyama.json
""",
    """
global/artists/so-taro.json
""",
    """
global/artists/aky_CG_Works.json
""",
    """
global/artists/sadaji.json
""",
    """
global/artists/kanahei.json
""",
    """
global/artists/Junsei_Kuninobu.json
""",
    """
global/artists/Tomomi_Kaneko.json
""",
    """
global/artists/Sakiko_Maeda.json
""",
    """
global/artists/Ken_Sugimori_Yusuke_Ohmura.json
""",
    """
global/artists/Fumie_Kittaka.json
""",
    """
global/artists/Nabana_Kensaku.json
""",
    """
global/artists/Avec_Yoko.json
""",
    """
global/artists/Mana_Ibe.json
""",
    """
global/artists/Huang_Tzu_En.json
""",
    """
global/artists/Misaki_Hashimoto.json
""",
    """
global/artists/Noriko_Uono.json
""",
    """
global/artists/take.json
""",
    """
global/artists/ConceptLab.json
""",
    """
global/artists/MPC_Film.json
""",
    """
global/artists/Framestore.json
""",
    """
global/artists/DemizuPosuka.json
""",
    """
global/artists/PLANETA.json
""",
    """
global/artists/PLANETA_Otani.json
""",
    """
global/artists/Emi_Ando.json
""",
    """
global/artists/2017_Pikachu_Project.json
""",
    """
global/artists/Nagimiso.json
""",
    """
global/artists/Arai_Kiriko.json
""",
    """
global/artists/Wintr_Wandr.json
""",
    """
global/artists/mingo.json
""",
    """
global/artists/Tonji_Matsuno.json
""",
    """
global/artists/satoma.json
""",
    """
global/artists/Bun_Toujo.json
""",
    """
global/artists/Yano_Keiji.json
""",
    """
global/artists/toi8.json
""",
    """
global/artists/Iori_Suzuki.json
""",
    """
global/artists/Nakamura_Ippan.json
""",
    """
global/artists/svlt.json
""",
    """
global/artists/Shinji_Higuchi.json
""",
    """
global/artists/Shinji_Higuchi__Sachiko_Eba.json
""",
    """
global/artists/Shinji_Higuchi__Sachiko_Eba_____.json
""",
    """
global/artists/Shinji_Higuchi__Noriko_Takaya.json
""",
    """
global/artists/Wataru_KawaharaDirec_Shinji_Higuchi.json
""",
    """
global/artists/Shinji_Higuchi__Sachiko_Eba__.json
""",
    """
global/artists/Kent_KanetsunaDirec_Shinji_Higuchi.json
""",
    """
global/artists/Hizuki_Misono.json
""",
    """
global/artists/Mikio_Menjo.json
""",
    """
global/artists/Sachi_Matoba.json
""",
    """
global/artists/Yuichi_Sawayama.json
""",
    """
global/artists/hanabushi.json
""",
    """
global/artists/KYUPIYAMA.json
""",
    """
global/artists/Saki_Hayashiro.json
""",
    """
global/artists/Nobuhiro_Imagawa.json
""",
    """
global/artists/Shinya_Mizuno.json
""",
    """
global/artists/Aliya_Chen.json
""",
    """
global/artists/Tetsuo_Hara.json
""",
    """
global/artists/Kamome_Shirahama.json
""",
    """
global/artists/MARINA_Chikazawa.json
""",
    """
global/artists/Narano.json
""",
    """
global/artists/PLANETA_Hiiragi.json
""",
    """
global/artists/Megumi_Higuchi.json
""",
    """
global/artists/Po-Suzuki.json
""",
    """
global/artists/Atsuya_Uki.json
""",
    """
global/artists/KG-2000.json
""",
    """
global/artists/Oku.json
""",
    """
global/artists/Felicia_Chen.json
""",
    """
global/artists/Eri_Kamei.json
""",
    """
global/artists/NobusawaMochipuyo.json
""",
    """
global/artists/Ebila.json
""",
    """
global/artists/Nabatame_Kazutaka.json
""",
    """
global/artists/Akino_Fukuji.json
""",
    """
global/artists/Julie_Hang.json
""",
    """
global/artists/Heisuke_Kitazawa.json
""",
    """
global/artists/Hoshino_KURO.json
""",
    """
global/artists/Iwamoto05.json
""",
    """
global/artists/Katsunori_Sato.json
""",
    """
global/artists/Minato.json
""",
    """
global/artists/Natsumi_Miyanose.json
""",
    """
global/artists/Acorviart.json
""",
    """
global/artists/Ito_Kyoko.json
""",
    """
global/artists/Anderson.json
""",
    """
global/artists/Yamazaki_Rei.json
""",
    """
global/artists/Kazuki_Minami.json
""",
    """
global/artists/zig.json
""",
    """
global/artists/Izucch.json
""",
    """
global/artists/DrOoyama.json
""",
    """
global/artists/GAME_FREAK_inc.json
""",
    """
global/artists/Ken_Sudimori.json
""",
    """
global/artists/Mosakazu_Fukuda.json
""",
    """
global/artists/Nobuyuki_Fujimoto.json
""",
    """
global/artists/Keiko_Moritsugu.json
""",
    """
global/artists/MUGENUP.json
""",
    """
global/artists/Hasegawa_Saki.json
""",
    """
global/artists/Mika_Pikazo.json
""",
    """
global/artists/Kinu_Nishimura.json
""",
    """
global/artists/DAG_Inc.json
""",
    """
global/artists/Yusuke_Kozaki.json
""",
    """
global/artists/The_Pokmon_Company_Art_Team.json
""",
    """
global/artists/Illus__Direc_The_Pokmon_Company_Art_Team.json
""",
    """
global/artists/Jumpei_Akasaka.json
""",
  )

  fun seriesJson(lang: String): String? =
    EmbeddedResourceLoader.readText("composeResources/files/tcgdex/${lang.lowercase()}/series.json")

  fun setsJson(lang: String): String? =
    EmbeddedResourceLoader.readText("composeResources/files/tcgdex/${lang.lowercase()}/sets.json")

  fun setDetailsJson(lang: String, setId: String): String? =
    EmbeddedResourceLoader.readText("composeResources/files/tcgdex/${lang.lowercase()}/sets/$setId.json")

  fun illustratorsIndexJson(): String? =
    EmbeddedResourceLoader.readText("composeResources/illustrators/global/illustrators-index.json")

  fun illustratorCollectionJson(artistFileName: String): String? =
    EmbeddedResourceLoader.readText("composeResources/illustrators/$artistFileName")

  fun illustratorArtistFiles(): List<String> = artistFiles
}

